### ISSUE TITLE
LGTM: semantic checker issues found in vw python & html/js code

### ISSUE THREAD

**Issue by arielf** [VowpalWabbit/vowpal_wabbit#1442]
lgtm found several semantic issues with some of our python code in the tree
(unfortunately, they don't support C/C++ yet, but their python/js catches seem to be pretty good):

   https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/alerts/?mode=list

Files with issues:
- utl/vw-hyperopt.py
- demo/recall_tree/wikipara/WikiExtractor.py
- python/vowpalwabbit/pyvw.py
- python/vowpalwabbit/sklearn_vw.py
- utl/active_interactor.py
- utl/vw-lda
- utl/vw-validate.html

Issues include Loop variable capture, call to non-callable, nested loops using same variable, use before set and more...

**Comment by JohnLangford** [comment]
I see C++ issues deeper in the warnings.  @Scott-Graham-Bose do you want to look through the python ones?  I'll handle the C++ ones.

**Comment by Scott-Graham-Bose** [comment]
i can take a look

**Comment by sjvs** [comment]
Hi @Scott-Graham-Bose, @JohnLangford, @arielf. Glad to see that you're enjoying LGTM! I just came across this issue and wanted to mention that we do now support C/C++ analysis. Your project's C++ code has in fact already been analysed by LGTM; here's an overview of just those alerts: https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/alerts/?mode=list&lang=cpp

I see you've already set up some CI checks for pull requests; it's easy to add automatic code review by LGTM as well! Repository admins can do that from this page: https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/ci/

Here's an example of how LGTM is helping the AMPHTML project with automatic code review: https://github.com/ampproject/amphtml/pull/13060

**Comment by arielf** [comment]
Looks like quite a few (84) good C++ semantic issues that will be good to fix.

**Comment by Scott-Graham-Bose** [comment]
#1476 PR to address these

**Comment by JohnLangford** [comment]
I'm running into an issue trying to use lgtm.  In essence, it seems like the analysis is quite out of date.  If I go to this:  https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/alerts/?mode=list&lang=cpp URL, I only see the analysis from 5 days ago (a June 27 checkin).  Why doesn't it autorefresh against the most current?  And how can it be made to update faster?

**Comment by sjvs** [comment]
Hi @JohnLangford! As is shown [at the top of that page you linked](https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/alerts/?mode=list&lang=cpp), those are indeed the active alerts as of `d177f77`. Looking at the [GitHub commit history](https://github.com/JohnLangford/vowpal_wabbit/commits/master), that was the most recent commit until `a9bba04` was committed about 15 hours ago (I can't see when that was pushed to GitHub exactly). Since then, you added another two commits.

At the moment, LGTM continuously analyses just under 80k repositories. To avoid overloading GitHub, we poll every one of these repositories for new changes once roughly every 24 hours (on a randomised schedule). The last time we polled the `vowpal_wabbit` repo was yesterday evening at 17:16:11 UTC. That's why your more recent commits haven't been analysed yet.

There's an easy way to get (much!) quicker feedback on your changes: enable automatic code review for pull requests. Here are two examples of how that works for two other projects: [AMPHTML](https://github.com/ampproject/amphtml/pull/13060) and [Systemd](https://github.com/systemd/systemd/pull/9438). If you enable PR integration, LGTM will analyse the commits as soon as a PR is opened/updated. This means you get results quicker, and more importantly: before any problems are merged into master :slightly_smiling_face:. You can enable automatic code review for PRs here: https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/ci/

I've also just trigger another poll manually now to get you the latest results on `master` as well. Let me know if there's anything else I can help with :slightly_smiling_face:

**Comment by JohnLangford** [comment]
Thanks.    I'll look into setting up the continuous integration in an hour or two.

**Comment by JohnLangford** [comment]
FYI, I've added LGTM to the CI checks. 
@deaktator @jmorra you may be heartened to know that the java code passes with flying colors :-)

I've reduced the set of C++ issues to a handful that I'll whittle down further over time.  @Scott-Graham-Bose it seems like there are still some python issues beyond your existing patch.   Perhaps you can look into them if you can spare the time.

**Comment by JohnLangford** [comment]
(Some of the python is probably stuff I need to look into as well.)

**Comment by sjvs** [comment]
Hi @JohnLangford! I just noticed you also have a good number of lines of C# code. We're currently testing out our C# analysis technology on LGTM; I hope you don't mind that I've added you to the closed beta. Results are now available here: https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/alerts/?mode=tree&lang=csharp.

How's the automatic code review for pull requests working for you? Thoughts/comments/suggestions are always welcome!

**Comment by JohnLangford** [comment]
The automatic code review is great.

Thanks for putting us in the C# analysis mode as well---looks handy.

-John

**Comment by Scott-Graham-Bose** [comment]
I've created a PR which updates some of code to resolve the warnings in the main python code, however there are more problems with python code in the demo and utl directories.

Two of the files generating a large portion of warnings are:
1. demo/recall_tree/wikipara/WikiExtractor.py
2. utl/active_interactor.py

WikiExtractor seems to be an external piece of code not maintained here, so my preference would be to remove it and provide a link to where to find it in the readme for that folder.

active_interactor is a bit difficult for me to parse, and I'm not sure it is in a currently working state. If this is functionality we want to maintain it would be worth overhauling it to make sure it's doing what we want and cleaning up the code.

In general I'm wondering if we should exclude the demo directory from these types of checks. I could see arguments either way.

**Comment by JohnLangford** [comment]
@sjvs , it seems lgtm is suffering spurious fails.  See #1533  Is this a known issue?

**Comment by sjvs** [comment]
Hi @JohnLangford: my best guess is that there was a network outage at our cloud provider. Both C# and Java analysis timed out on fetching external dependencies (from nuget.org and repo.maven.apache.org, respectively). I've now retriggered the analysis for that PR and will keep an eye on it. If it happens again then we should obviously have a closer look... Thanks for letting me know!

**Comment by sjvs** [comment]
It turns out that there are wider connectivity issues: https://discuss.lgtm.com/t/lgtm-has-been-failing-to-get-packages-from-archive-ubuntu-com-since-yesterday/1112

We're investigating and will report back in the forum topic.

**Comment by jackgerrits** [comment]
Closing this as LGTM is working normally now
