### ISSUE TITLE
progress argument with daemon logging 

### ISSUE THREAD

**Issue by matanster** [VowpalWabbit/vowpal_wabbit#1578]
I'm running a CB bagging model, deliberately setting `--progress 1` for a certain audit/demo scenario. For some reason the daemon doesn't entirely comply, and issues its summary line only every 10 messages. This is not specific to the bagging algorithm.

At least it looks like that to me:

![image](https://user-images.githubusercontent.com/4996067/44619594-11ac5b80-a892-11e8-9cc3-539f3230364c.png)

When training, `--progress 1` does have the anticipated effect. Would it be a good idea to submit a patch to revert this to allowing per message reporting? or am I just misinterpreting the example counter column? I think it would be quite nice to have per message audit if only for tutorials, demos, and integration environments.

Thanks for commenting!

**Comment by JohnLangford** [comment]
This seems like a bug, so a patch is welcome.

**Comment by arielf** [comment]
Does `--progress` work correctly when options are changed? Dropped?

Only slightly related: one thing that always bothered me about `--progress` is that its frequency is tied to the total weight rather than example count which is more user-intuitive.  If I could change this, I would.

**Comment by matanster** [comment]
@arielf I've not noticed trouble with `--progress` other than this one, but I didn't realize it was sticky (?!) in the model until your last comment here.

**Comment by jackgerrits** [comment]
`--progress` is not defined as a keep option so I don't think that was the issue. 

What I think was the issue here is that in daemon mode VW forks off to several children to listen for incoming connections, and those children all have their output disabled except for 1. The OS then chooses how to distribute incoming connectiond to the listener that was created prior to forking. One way of distributing the output is round robin. The default number of children in VW is 10. So you were seeing the output for only one of the children.

I encountered a regression in daemon mode when testing this out which I have fixed in PR #3464. After that fix everything seems to work as expected with `--num_children 1`
