### ISSUE TITLE
Case sensitivity of namespace (first letter) in --keep option

### ISSUE THREAD

**Issue by varunparmar** [VowpalWabbit/vowpal_wabbit#1611]
I am struggling with an issue related to --keep or --ignore option of vowel wabbit. Basically, keep option is excluding all namespaces starting with small caps, but not excluding the ones with capital letters.

```
time <vw_file> vw --loss_function logistic --cache_file --passes 4 --ftrl --l1 1.0 --l2 0.1 --ftrl_alpha 0.1 --ftrl_beta 1.0 --keep j --keep l --keep q --keep u --keep w --keep A --final_regressor <model_path>
time cat <vw_file> | vw --link logistic -t -I <model> --invert_hash <human_readable model>
grep <human_readable_model> awk -F"namespace" {'print $1'} | sort | uniq
A B C D E F j l q u w
```

Don't expect B-F in this list. {b-f}namespaces are successfully excluded.

**Comment by arielf** [comment]
Hi @varunparmar 

A bit challenging t help with so many placeholders.

Can you provide a reproducible and minimal example?

(Also note that you can't `--invert_hash` a binary model. Original feature names are not stored in the model. You can only do it what you have a data set.)

**Comment by trufanov-nok** [comment]
I check this and can't reproduce the problem in --keep
Note, you can use `--keep jlquwA` instead of `--keep j --keep l --keep q --keep u --keep w --keep A`
Make sure you're working with up-to-date cache by specifying `-k` after `-c` or `--cache_file data.cache`
` --invert_hash` will work if your `< vw_file >` is the same but it may allocate a lot of RAM. you can try `--audit_regressor` option instead
Are you sure in your awk command? Namespaces are separated with ^ character

**Comment by JohnLangford** [comment]
I suspect the problem here is in the shell rather than vw.   I'm closing this due to lack of response, but please reopen if an issue continues to exist.
