### ISSUE TITLE
library/test_search segfault on master

### ISSUE THREAD

**Issue by jprobichaud** [VowpalWabbit/vowpal_wabbit#1671]
Perhaps caused by the same issue as issue "Hook interface" #1413, building vw and then doing 
```
cd library
make
./test_search
``` 
Also results in a core dump 

This is on ArchLinux, 64bit, with GCC 8.2.1 and Boost 1.68

**Comment by jprobichaud** [comment]
adding print statements, I identified that the segfault happens "between" these two lines, just after the get_task_data:
```
     HookTask::task_data* d = sch.get_task_data<HookTask::task_data>();
     d->run_f = _search_run_fn;
```

It seems to be the case also when executing from python

**Comment by jprobichaud** [comment]
With the recent updates to master, we now get some extra details:
```
$ library/test_search 


##### train() #####

warning: task should not set options except in initialize function!
terminate called after throwing an instance of 'VW::vw_exception'
  what():  using LDF and actions costs is not yet implemented; turn off action costs
Aborted (core dumped)
```

**Comment by jprobichaud** [comment]
I coulnd't have a chance to spend some time on this again, will anyone from the "official" team be able to have a look?

**Comment by lokitoth** [comment]
I've been looking at the other hook task issue and it seems like this may be the same issue. 

The higher-level issue is that we explicitly disable "hook" - which seems to have been around for a while. That is fixed by removing the check in search.cc's setup(). The next-level issue is that this uses the old API for multi-line example, which fails the multi-line test. Switching to multi_ex as input fixes that. The underlying issue is that setting the right function-pointers in SearchTask's init (in libsearch.h) does not seem to actually set them in the task-object that hook-task is looking into.

Still trying to debug why that is going on.

**Comment by lokitoth** [comment]
I believe I have a fix for this - just need to do a bit more validation under Linux. After that will check whether there is more work (I expect there will be, to propagate the API changes through the Python library).

Here's the branch in my fork: lokitoth/vowpal_wabbit:dev/Fix-SearchHookTaskCppLibrary
cc @jprobichaud

**Comment by jprobichaud** [comment]
wonderful, thanks a lot for looking into it!  I will try to recompile my
C++ code later this week on your branch.  I'm working exclusively on linux
so this will hopefully test that side of the house a bit more.

thanks again!
