### ISSUE TITLE
8.6.1: --cb_adf silently makes two examples when single example has > 255 actions

### ISSUE THREAD

**Issue by maxpagels** [VowpalWabbit/vowpal_wabbit#1739]
#### Describe the bug
In VW ver. 8.6.1, when using `--cb_adf` and specifying a multiline example with over 254 actions, actions # 255 and beyond are silently interpreted as a new example

#### To Reproduce
Data used: https://gist.github.com/maxpagels/d432e5e16fdaef899c58d6c0b6795c3d
Run: `vw test.vw --cb_adf --progress 1`

#### Expected behavior
If 254 actions is a hard limit, a warning would perhaps be a good idea?

#### Observed Behavior
The output of VW indicates that the multiline example is in fact interpreted as two examples:

```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
    n.a.     n.a.            1            1.0  unknown        0:0...     1012
    n.a.     n.a.            2            2.0  unknown        0:0...        4

finished run
number of examples = 2
weighted example sum = 2.000000
weighted label sum = 0.000000
average loss = n.a.
total feature number = 1016
```

Removing the last action from the input data ( resulting in 254 actions), works as expected:
```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
    n.a.     n.a.            1            1.0  unknown        0:0...     1012

finished run
number of examples = 1
weighted example sum = 1.000000
weighted label sum = 0.000000
average loss = n.a.
total feature number = 1012
```

#### Environment
OS X, VW 8.6.1, CLI

**Comment by jackgerrits** [comment]
Hi @maxpagels, thanks for the clear repro steps. It was very useful in fixing this. I've just created a PR (#1777) which addresses this issue by removing the limit on the number of examples that can be in a multi line example. The issue you are seeing was due to the fact a fixed size ring buffer was used to store these examples, and the default size is 256. You are able to pass a different size for this ring buffer by passing an argument for `--ring_size` if you would like to be unblocked sooner. Otherwise once the PR is merged the limit should be lifted.
