### ISSUE TITLE
Json format in python bindings is not supported

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#1756]
#### Describe the bug
json (dsjson as well) format is not supported for python binding

#### To Reproduce
from vowpalwabbit import pyvw
_vw = pyvw.vw('--cb_adf --dsjson')
_vw.learn('{"_label_cost":-1.0,"_label_probability":0.850000024,"_label_Action":4,"_labelIndex":3,"o":[{"EventId":"id-01","v":1.0,"DeferredAction":false}],"Timestamp":"2018-12-17T00:00:00.3930000Z","EventId":"id-01","DeferredAction":false,"a":[4,2,3,1],"c":{"User":{"f1":0},"_multi":[{"mf1":1},{"mf1":2},{"mf1":3},{"mf1":3}]},"p":[0.85,0.05,0.05,0.05]}')

#### Expected behavior
Either:
1) successful learning
or:
2) unsuccessful initialization (i.e. 'dsjson option is not supported')

#### Observed Behavior
Vw intalization is succeeded, but got the following error after the learn call:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/vowpalwabbit-8.6.1-py3.6-linux-x86_64.egg/vowpalwabbit/pyvw.py", line 130, in learn
    self.learn_string(ec)
RuntimeError: This reduction does not support single-line examples.

Message can vary depends on input data, but the root cause seems to be that learn call stack is always like this:

pyvw::learn -> learn_string ->my_learn_string -> VW::read_example -> VW::read_line
and there is no chance for read_line_json to be called

#### Environment
8.6.1 python bindings, Debian 9.5

**Comment by jackgerrits** [comment]
This is trickier than I first imagined. The way different parsers are exposed is through a function pointer, this function pointer doesn't accept a string but does the reading itself from whatever the input file is. So there isn't a generic way to go from string to list of examples using the set parser. I'll keep thinking about it but I think in order to get this functionality turned on I may need to rearrange some things.
