### ISSUE TITLE
Have a single test harness for acceptance testing

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/vowpal_wabbit#1803]
VW currently have two acceptance test harnesses. The first one is ` tests\RunTests`  which is a perl script. The second one is `cs\unitests\RunTests.tt`.

The second one parses the test definitions from the first one and have an exclusion list based mostly on tests it can't parse the definition from. 

This leads to surprising CI failures when adding a new test that can't be handled by the second harness.

One of those two must be eliminated without removing our ability to test on windows. This sparks no joy on our contributors.

**Comment by jackgerrits** [comment]
Is it possible to run the perl test harness on Windows easily?

**Comment by lokitoth** [comment]
Is the goal to test "VW the library", or "VW the executable"?

The current run-tests in perl mode tests the latter. I am not super sure how to describe the C# version of these tests.

**Comment by kumpera** [comment]
The goal is to reduce friction when adding tests to VW.

I'd expect that whether we test VW as a library or executable should not matter for the tests that don't care about this particular aspect.

Now, if RunTest is a mix of test that do and tests that don't care whether we're testing as a library, splitting along those lines is another way of addressing this issue.

**Comment by lokitoth** [comment]
Makes sense; I was just thinking about it from a roadmap standpoint. It might be that on different languages/platforms we might have different expectations of what the important ship vehicles are and which ones we need to implement these tests for first.

**Comment by jackgerrits** [comment]
We discussed this issue and the multiple different harnesses are used to test different areas. That said, we should try and ensure the run_tests.py suite runs on Windows in the same way as linux. #3588 tracks this. Additionally, to avoid frustration of floating point differences between systems #3589 is created.

The single testing entrypoint is different because it differs per targeted language and is extra confusing since all languages are bespoke. For standard core behavior the cmake generated ctest targets should provide most coverage. The targets are invoked directly due to the ctest experience being suboptimal.
