### ISSUE TITLE
Replace signed 'char' uses with 'unsigned char' or 'int8_t'

### ISSUE THREAD

**Issue by lokitoth** [VowpalWabbit/vowpal_wabbit#1868]
It is likely fairly rare that we need an actual 8-bit integral value. If we do need one, we should prefer the explicitly-sized `int8_t`, that way we do not confuse "this is a character in a string, which is naturally unsigned", especially if we want to use it as an array index, as opposed to "this is an integer that is signed and one byte in size".

This will prevent us from having errors like trying to index into arrays using a signed char (which breaks for any value > 127), e.g. indexing into feature_space in the json parser.

**Comment by jackgerrits** [comment]
Perhaps using `uint8_t` or `int8_t` explicitly would be clearer? Most places we use a char we actually just want an unsigned byte, right?

**Comment by lokitoth** [comment]
From a cursory look, it seems that most of the cases are either strings or namespace index, so we could use `namespace_index` where it makes sense. The main thrust of this is to ensure that any place where we are treating the chars as elements of strings, we should always use `unsigned char`, or explicitly declare it to be a number with a fixed size.

**Comment by Sharad24** [comment]
@jackgerrits Could you point to an example of a case matching this issue? It looks like there are _very_ few of them present now.

**Comment by jackgerrits** [comment]
In example_predict.h you'll notice there is a typedef of `namespace_index` to `unsigned char`. Namespace indices are the majority offender for this issue I'd say.

So this issue is mostly a work item about auditing usages of namespace indices and making sure that we are doing the correct thing. Namespaces are stored as a `std::string`, and so is a list of signed characters. But we use them as an unsigned integer to index an array. Processing the interaction is here and you'll notice plenty of casts. https://github.com/VowpalWabbit/vowpal_wabbit/blob/bd98471f330ed5aae2dea5bdb3610761c396786e/vowpalwabbit/interactions_predict.h#L98

I think it might make sense to turn interactions into a vector of `uint8_t`, @lokitoth thoughts?

**Comment by Sharad24** [comment]
Ah gotcha, thanks! Will take a look

**Comment by olgavrou** [comment]
@jackgerrits can we close this issue?

**Comment by jackgerrits** [comment]
Sounds good!
