### ISSUE TITLE
--invert_hash ambiguity

### ISSUE THREAD

**Issue by lokitoth** [VowpalWabbit/vowpal_wabbit#1960]
#### Describe the bug
When there is ambiguity between ns^feature_name and a feature with name "ns^feature_name"  in a single example, --invert_hash only shows the hash of the first one.

#### To Reproduce
Input files:
input1.txt
`1 | ns^abc |ns abc`

input2.txt
`1 |ns abc | ns^abc`

1. vw -d input1.txt --invert_hash inv_hash1.txt --readable_model readable1.txt
2. vw -d input2.txt --invert_hash inv_hash2.txt --readable_model readable2.txt

#### Expected behavior
inv_hash1.txt and inv_hash2.txt are the same and contain hashes for both features (along with constant)

#### Observed Behavior
inv_hash1.txt shows hash (92529) for []^[ns^abc], and inv_hash2.txt (16258) for [ns]^[abc]

#### Environment
This should be independent of OS/language, but is tested on master as of today.

**Comment by jackgerrits** [comment]
Another way to handle this could be to provide a csv or json based output for the weights of the regressor.

**Comment by jackgerrits** [comment]
People most likely depend on current behavior so we should not simply change the output in place. It's not a priority to fix this and since a fix would need to come in in a parallel usage mode it is more of a feature request. Producing a JSON output of readable names to values would be a machine readable and non-ambiguous option. This is certainly a patches welcome. Closing This specific issue as we don't want to break existing usage.
