### ISSUE TITLE
strange results in varinfo

### ISSUE THREAD

**Issue by adischw** [VowpalWabbit/vowpal_wabbit#2044]
Hi! i’m pretty new to VW and after reading all the relevant documentation i'm still not clear about the varinfo..
I converted my features to a VW format where i have separate namespaces for every feature and they are all strings:
`1 |B B_09e6fb92eadea53ec206e05e4aea5654 |C C_2171791366 |D D_830995 |E E_2082213077 |F F_830995 |G G_283.0 |H H_Firefox |I I_MacOS |J J_1 |K K_100`
When i use varinfo i get strange results. i expected to see the features as the namespaces (e.g.: A, B, C,…) and not every possible feature value (see weights_details.txt).
Any insights/advice?

**Comment by jackgerrits** [comment]
Hi @adischw,

When I run `vw-varinfo` with the example you provided I get the following.

```sh
$ echo '1 |B B_09e6fb92eadea53ec206e05e4aea5654 |C C_2171791366 |D D_830995 |E E_2082213077  |F F_830995 |G G_283.0 |H H_Firefox |I I_MacOS |J J_1 |K K_100' > train.txt
$ ./vw-varinfo train.txt

FeatureName                                HashVal   MinVal   MaxVal    Weight   RelScore
B^B_09e6fb92eadea53ec206e05e4aea5654        195592     0.00     1.00   +0.0736    100.00%
C^C_2171791366                              205396     0.00     1.00   +0.0736    100.00%
D^D_830995                                   98910     0.00     1.00   +0.0736    100.00%
E^E_2082213077                                  22     0.00     1.00   +0.0736    100.00%
F^F_830995                                    7950     0.00     1.00   +0.0736    100.00%
G^G_283.0                                    52044     0.00     1.00   +0.0736    100.00%
H^H_Firefox                                 198129     0.00     1.00   +0.0736    100.00%
I^I_MacOS                                    63088     0.00     1.00   +0.0736    100.00%
J^J_1                                       226067     0.00     1.00   +0.0736    100.00%
K^K_100                                     182262     0.00     1.00   +0.0736    100.00%
Constant                                    116060     0.00     0.00   +0.0736      0.00%
```

The feature name is shown as namespace^featurename, so for `B^B_09e6fb92eadea53ec206e05e4aea5654` it is a feature `B_09e6fb92eadea53ec206e05e4aea5654` in namespace `B`.

Namespaces are usually used when you want to cross features to create new features which could be done as a command line parameter like so: `--interactions BC`. This would cross all features in namespace `B` with namespace `C`. We can use `vw-varinfo` to show this, since it supports forwarding options to VW:

```sh
$ ./vw-varinfo -q BC train.txt
FeatureName                                                HashVal   MinVal   MaxVal    Weight   RelScore
B^B_09e6fb92eadea53ec206e05e4aea5654                        195592     0.00     1.00   +0.0686    100.00%
B^B_09e6fb92eadea53ec206e05e4aea5654*C^C_2171791366         123596     0.00     0.00   +0.0686    100.00%
C^C_2171791366                                              205396     0.00     1.00   +0.0686    100.00%
D^D_830995                                                   98910     0.00     1.00   +0.0686    100.00%
E^E_2082213077                                                  22     0.00     1.00   +0.0686    100.00%
F^F_830995                                                    7950     0.00     1.00   +0.0686    100.00%
G^G_283.0                                                    52044     0.00     1.00   +0.0686    100.00%
H^H_Firefox                                                 198129     0.00     1.00   +0.0686    100.00%
I^I_MacOS                                                    63088     0.00     1.00   +0.0686    100.00%
J^J_1                                                       226067     0.00     1.00   +0.0686    100.00%
K^K_100                                                     182262     0.00     1.00   +0.0686    100.00%
Constant                                                    116060     0.00     0.00   +0.0686      0.00%
```

The columns are describing several things:
HashVal - The internal hashed index vw uses for this feature
MinVal - The minimum value seen for this value in the data (or 0 if it is positive)
MaxVal - The maximum value seen for this value in the data (or 0 if it is negative)
Weight - The weight stored in the model for this feature

**Comment by jackgerrits** [comment]
I'm going to go ahead and close this @adischw, if you have any further questions feel free to reopen.
