### ISSUE TITLE
csoaa predicted an invalid class

### ISSUE THREAD

**Issue by martinpopel** [VowpalWabbit/vowpal_wabbit#205]
```
echo "1:0 2 3 | a
1 2 3:0 | b" | vw --csoaa 3
```

results in _warning: csoaa predicted an invalid class_ while

```
echo "1:0 2:1 3:1 | a
1:1 2:1 3:0 | b" | vw --csoaa 3
```

goes ok.

The documentation https://github.com/JohnLangford/vowpal_wabbit/wiki/Cost-Sensitive-One-Against-All-%28csoaa%29-multi-class-example says that _"default cost, when omitted is 1.0"_
(Just adding colons without costs does not help.)

Either the documentation or the implementation is wrong.

**Comment by dhruvghulati** [comment]
I am getting this exact issue. I am guessing this may be because I have examples of the exact same features which have different costs for different labels.

My model is predicting the label "16" even though I only have training labels from 0 to 15.

```
warning: csoaa predicted an invalid class
NAN prediction in example 14545, forcing 0.000000
```

This happens across all my files, but I have attached a sample pipeline of training to test for one of my pipelines.

Commands run were:

vw --csoaa 16 closed_cost_1.dat -f closed_cost_1.model
vw -t -i closed_cost_1.model test.dat -p closed_cost_1.predict

[closed_cost_1.dat.txt](https://github.com/JohnLangford/vowpal_wabbit/files/409816/closed_cost_1.dat.txt)
[closed_cost_1.model.txt](https://github.com/JohnLangford/vowpal_wabbit/files/409818/closed_cost_1.model.txt)
[closed_cost_1.predict.txt](https://github.com/JohnLangford/vowpal_wabbit/files/409817/closed_cost_1.predict.txt)

No idea why this is the case - note that it does predict some values that are within my allowed values but overall everything has been defaulted to being this invalid class.
