### ISSUE TITLE
`--invert_hash` model output unclear (`--oaa`)

### ISSUE THREAD

**Issue by sophie-haynes** [VowpalWabbit/vowpal_wabbit#2077]
#### Describe the bug
When using the `--invert_hash` functionality of VW, specifically when constructing an `--oaa` multiclass model, there is some confusing output. If this is already documented in the wiki, I apologise for being unable to find it. However if it's not present, I'm happy add some notes to the docs if you pass the correct location for the modification :)

Let's say we have classes [1,2,3], when getting the model weights using `--invert_hash`,  it produces the following output (I think!):
*namespace* ^ *feature* [*class*]: *hash value* : *weight*
E.g. `text^a[1]:87850:-0.0915874`

However! The confusion comes in considering VW doesn't support **0** as a label, it appears the model weights start at 0/NA rather than 1.
E.g.
```
text^a:87840:-0.0742514
text^a[1]:87850:-0.0915874
```
Looking at the above sample, I had initially assumed the row without a class in square brackets was an overall feature importance. But later noticed the final class (in this example [3]) would never appear, only classes 1 & 2. Manual investigation of the feature weightings suggests that the unlabelled first row is class [1], the second row labelled as 1 is in fact class [2], and so on. 

#### To Reproduce
1. Used this specific command line `vw -k --oaa 16 -d major_train_strat --invert_hash major_READABLE.model`
2. Read the contents of `major_READABLE.model`

#### Expected behavior
Classes in the model output would match the labels passed in, rather than starting at 0. Given that n=16, sample would appear as follows:
```
text^a[1]:87840:-0.0742514
text^a[2]:87840:-0.0742514
...
text^a[15]:87840:-0.0742514
text^a[16]:87840:-0.0742514
```

#### Observed Behavior
The model classes start with an unannotated row for class 1, and the final class is represented as (n-1).
```
text^a:87840:-0.0742514
text^a[1]:87841:-0.0152896
text^a[2]:87842:-0.0843951
...
text^a[14]:87854:-0.0414668
text^a[15]:87855:0.0949629
```

#### Environment
What version of VW did you use? *8.5.0*
What OS or language did you use? *MacOS*

**Comment by jackgerrits** [comment]
The way `--oaa` works is that it uses a different learner for each of the classes. The way VW internally represents multiple learners is that original feature indices have an offset applied for each additional learner. Since this is an offset, it begins at 0 (implicit when the square brackets aren't present) and goes from there. So since it isn't actually the class, that explains why there is this mismatch of 1.

`--invert_hash` is similar to the output of `--audit`, (see [this wiki page](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Audit)), but I do not think we have specific docs for the output of `--invert_hash`.

Does that clear things up?

**Comment by jackgerrits** [comment]
I'm going to close this one @sophie-haynes, if you think there is still an issue here please reopen this.
