### ISSUE TITLE
--ring_size should be a hard limit for the number of examples

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2123]
Currently --ring_size specifies the initial pool size, but it will grow if it becomes empty. This should not be the default behavior, but it should be fixed size.

The issue is that tests rely on being able to wrap around the ring ("effectively infinite"), and break when there is a hard failure. Needs design: Possibly the right solution here is to make the limit optional, and have an "unlimited" default.

**Comment by jackgerrits** [comment]
If ring size is set explicitly then we use the capped behavior

**Comment by jackgerrits** [comment]
We have no way of knowing how large a multi_ex will be until it is done parsing. Because of this imposing a hard limit on the queue is a potential deadlock situation, and one we cannot detect and avoid. We would hit this if the multi_ex is larger than the allocated ring_size. Having an undetectable deadlock is not okay, so I want to push this change out until we have infrastructure to be able to know the multi_ex size and not get into this situation.

Memory usage is still bounded as it will level out as examples are parsed. The memory consumption is essentially a factor of the largest multi_ex that exists and how long the learning algo takes to drain examples from the queue.

**Comment by peterychang** [comment]
We currently have 2 very different workflows, which complicates this issue. Regardless of what the final design is, we will need to unify them
1. JSON parser
This parser reads in a single line of JSON and outputs a vector of examples. In the case of a multiline example, the vector contains all the examples. Example allocation occurs within the parser itself via a factory object
2. Text (maybe cached?) parser
This parser reads in a single line of input text and outputs a single example. In the case of a multiline example, each line is parsed individually and the full example is reassembled on the driver (learner.cc)

The most logical design would be to make the text/cached parser mimic the JSON parser's behavior, and have it output fully formed multiline examples at a time. As a longer-term goal, we should simply have an example, which can be a multiline example

**Comment by peterychang** [comment]
If we take futureproofing into consideration (ie: multiple parser threads) there are no small changes to fix the ring_size problem.

For example:
Assume we have the following setup
- 2 json parser threads
- ring-size == 4

Now, assume each thread is parsing a multi example with 4 actions each. Each thread has at least 1 example reserved, so neither thread will be able to complete its parsing; resulting in a deadlock.

We could add back-out logic; where if a parser fails to get an example from the pool and it doesn't have all of the available examples, then it would abort and return all examples back to the pool. This would work, but it would be incredibly inefficient since it can't account for parsed and in-flight examples into account.

The most straightforward way to solve the problem would be to refactor examples and eliminate the need for multiple examples in order to represent a multiline example.

A second method would be to create an object pool that can track the current status of all of its elements. This pool would need the ability to force a parser to back out and free all of its examples if necessary.
This option is smaller and more targeted but also far more intrusive, requiring additional hooks to be added to allow for the necessary bookkeeping.

**Comment by peterychang** [comment]
While not a perfect solution, a temporary workaround to this problem could be to cap the parsed examples queue size. This wouldn't give us the ability to enforce a hard cap, but it wouldn't be too far off. The max pool size in this case would be
`max_pool_size = max_queue_size + max_multiline_size * (num_learner_threads + num_parser_threads)`
