### ISSUE TITLE
Editing cache files

### ISSUE THREAD

**Issue by pmcvay** [VowpalWabbit/vowpal_wabbit#2210]
Is it possible to edit the cache file vw generates after reading a data file? I would like to change the only the labels for each point (the features stay the same) and the only way I have been able to do that so far is to edit the text file with the data and then reload into vw.

**Comment by jackgerrits** [comment]
There is no such tool available unfortunately. Cache files aren't intended to be edited, only produced and consumed by VW. I can see a tool like this being useful though, though creating something like this isn't really on the radar at the moment.

**Comment by pmcvay** [comment]
Could you point me in the direction to where I could figure out a hack? I'm kinda lost in the code base

**Comment by jackgerrits** [comment]
This is the reader function that is used when reading cache files: https://github.com/VowpalWabbit/vowpal_wabbit/blob/ae8d7241b56d55785e09f0b6e41506281b91f9b9/vowpalwabbit/cache.cc#L64
You can use this to understand the general structure of the cache file.

Depending on which reductions are being used there will be a different label parser. This defines how the label is read and written. The read cached label function is being called here:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/ae8d7241b56d55785e09f0b6e41506281b91f9b9/vowpalwabbit/cache.cc#L64

In the case of simple label you can find the implementation here: https://github.com/VowpalWabbit/vowpal_wabbit/blob/e1a05f483b0c9e35f6a039ed848433d24b6843c6/vowpalwabbit/simple_label.cc#L29

I don't believe there is a checksum for a cache file but I might be mistaken. These functions should help you understand how a cache file is laid out.

**Comment by jackgerrits** [comment]
I worked with Paul via email to come to a solution that suits him.

If others find this and want something similar, I have [a branch](https://github.com/jackgerrits/vowpal_wabbit/tree/overwrite_simple_labels_in_cache_file) that allows simple labels to be overwritten in a cache file. This branch is very hacky - you cannot use this for any normal VW functionality. Make sure you use a normal VW binary for creating the cache file and all normal training etc.

On to how to use this branch. Once you have your cache file and the file you provided with labels to overwrite with you can invoke the VW binary built out of that branch like so:
```sh
vw --cache_file <input_cache_file> --overwrite_cached_simple_labels_file <labels_file> --overwritten_cache_file <output_cache_file>
```
- `<input_cache_file>` is the original cache 
- `<labels_file>` is the file with new labels as you provided, one label per line. It must contain at least as many labels as you have examples, otherwise you'll get an error
- `<output_cache_file>` is the name of the new cache file to produce with the labels replaced
