### ISSUE TITLE
--ngram option

### ISSUE THREAD

**Issue by serjioteh** [VowpalWabbit/vowpal_wabbit#2230]
#### Describe the bug
From wiki doc:
"--ngram arg              Generate N grams. 
                         To target a specific namespace write its name as a prefix to arg 
                         (e.g. --ngram a2 --ngram c3)."

Writing a specific namespace as a prefix to arg doesn't affect on result.

#### To Reproduce
1. To train the model with --ngram option and without -> you'll get the same loss
2. Use --audit option to see the features -> no ngrams
3. varinfo generates identical files

#### Environment
vw 8.8.0
Ubuntu 18.04 LTS

#### Additional context
vw 8.7 has the same behavior

**Comment by yannstad** [comment]
Hi @serjioteh 

I tried to reproduce and I do not see the issue.

**Input data for my test:**
`1 1.0 |MetricFeatures:3.28 height:1.5 length:2.0 |Says black with white stripes |OtherFeatures NumberOfLegs:4.0 HasStripes`
(chosen from the [wiki](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format))

**VW version tested:**
Build from source (commit [c88fd5605aefd3df6b854f49fea714f0f741180c](https://github.com/VowpalWabbit/vowpal_wabbit/commit/c88fd5605aefd3df6b854f49fea714f0f741180c))

**Command lines tested:**
1. Baseline: `vw -d train.dat --audit`
2. Generates 2-grams for all namespaces: `vw -d train.dat --audit --ngram 2`
3. Generates 2-grams for M namespaces: `vw -d train.dat --audit --ngram M2`

Unlike what you reported, I actually see the ngrams generated in cases 2 and 3.

Can you possibly provide concrete information in order to reproduce, including training data and vw command line?

Thanks

**Comment by serjioteh** [comment]
It seems that the problem is in vw-varinfo2.py script.
It works correctly with --ngram 2 and --ngram A2 B2 C2 options on small dataset. But when I run vw on the whole big dataset output files will be identical for --ngram A2 B2 C2 option and without it.
Nevertheless script will generate big output file with feature importance with --ngram 2 option and I can see inside the file 3-grams,4-grams,5-grams. It was run with --ngram 2!
A_text^son^cant^dad^и^точка^продажа^sound^microwaves^phospenes      515873      1.00    1.00    1.87     100.00

Running vw with test audit options I can see that ngrams option works correctly.
