### ISSUE TITLE
Documentation of pyvw.py

### ISSUE THREAD

**Issue by Smit-create** [VowpalWabbit/vowpal_wabbit#2267]
#### Describe the bug
The documentation of `pyvw.py` can be corrected i.e to add essential details like Parameters, Return type, Examples etc. The documentation of `sklearn_vw.py` provides with this essential details and becomes easy to use at the user end. We can also follow the specific patter of documenation in all `.py `files as in https://numpydoc.readthedocs.io/en/latest/format.html#sections. Is it a good idea?

**Comment by jackgerrits** [comment]
100% agree, the documentation can be improved. I do like the suggestion of following the sections that numpy uses, that seems quite complete. Let's see if any others have opinions here. 

By the way, docs are hosted here: https://vowpalwabbit.org/docs/vowpal_wabbit/python/html/
They are currently updated manually which is why they are out of date. I've started work on automatic updating, I have CI that generates the docs so I just need to implement the updating.

**Comment by Smit-create** [comment]
Thanks @jackgerrits . Okay lets wait, once everyone agrees, I will open a PR of the same

**Comment by Smit-create** [comment]
> By the way, docs are hosted here: https://vowpalwabbit.org/docs/vowpal_wabbit/python/html/

Yes, seems that `pyvw.py` documentation needs an attention.

**Comment by ARDivekar** [comment]
Adding another issue: the documentation pages for https://vowpal-wabbit.readthedocs.io/en/latest/vowpalwabbit.pyvw.html and https://vowpal-wabbit.readthedocs.io/en/latest/vowpalwabbit.sklearn.html seem to be empty?? Seems like that's a miss.

**Comment by thealphadollar** [comment]
@jackgerrits Is this issue open for taking up?

**Comment by Smit-create** [comment]
@thealphadollar I am working on it.

**Comment by thealphadollar** [comment]
Great 😀
