### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by mebaran** [VowpalWabbit/vowpal_wabbit#2284]
I would like to use vowpal wabbit on ARM.  However the only thing stopping me is the sse2 and sse flags in the CMakeList.txt config.  Is there any reason not to use -march=native to support the best floating point instructions on all architectures?

Most tests seem to pass when I do this except some concerning active simulation.  Anything I can do to help add the support?

Link to test failure output for the two tests that failed (which seemed to be just a minor change in the calculation):  https://gist.github.com/mebaran/ae9d22a1d03a760aadee99d1b3abe3e1

**Comment by jackgerrits** [comment]
Hi @mebaran,

Supporting ARM is really important, thanks for bringing this up. I wasn't aware of `-march=native`, seems like it would be really useful for making the builds simpler for cross platform. I'll look into changing our build script for this.

Briefly looking at the test output, it seems like the failure is caused by float differences. I'm not surprised given it was run on ARM, I've noticed similar float differences between x86 processors. Did you run the tests with an epsilon value for float comparisons?

Ideally, I'd also like CI to run for ARM but that may take a bit longer.

**Comment by mebaran** [comment]
Yes, -march=native will activate the ideal floating point system for each binary built.  The tests were all run via make test.

In terms of CI, ARM machines are pretty easy to come by these days and Travis CI has native support.  The build script executed cleanly on ARM so I would bet it would be minimal effort to support actually (assuming your CI is run on top of Github Travis)

**Comment by jackgerrits** [comment]
We've been investing in CI on Azure DevOps, from a quick look it doesn't seem that easy to run ARM there. Might be worth using travis for the easy integration. I'll discuss that and come to a solution

**Comment by jackgerrits** [comment]
I tested changing the build flags to use `-march=native` and on my machine some of the tests begin to fail. I assume this is because some floating point logic changed and sufficiently changes the results so we start to fail in some cases. It would be reasonable to add a CMake option to allow overriding the current flags with `-march=native`

**Comment by pardont** [comment]
Is there any update?

**Comment by jackgerrits** [comment]
ARM should be supported in 8.10.0, let me know if you have any issues.
