### ISSUE TITLE
Chaining SGD and BFGS fails if used with save_resume/preserve_performance_counters

### ISSUE THREAD

**Issue by eisber** [VowpalWabbit/vowpal_wabbit#2342]
#### Describe the bug
Chaining SGD and BFGS fails if used with save_resume/preserve_performance_counters.

#### To Reproduce
ARGS="--passes 5 --holdout_off --loss_function quantile -q :: -l 0.1"
# CRASHES
# ARGS="--passes 5 --holdout_off --loss_function quantile -q :: -l 0.1 --save_resume --preserve_performance_counters"
/mnt/c/work/vowpal_wabbit/vowpalwabbit/vw $ARGS -k --cache_file /tmp/marcozo-repro.cache -f /tmp/repro1.vw /tmp/traizines.vw
/mnt/c/work/vowpal_wabbit/vowpalwabbit/vw $ARGS --bfgs -k --cache_file /tmp/marcozo-repro.cache -i /tmp/repro1.vw -f /tmp/repro2.vw /tmp/traizines.vw

#### Expected behavior
Don't crash.

#### Observed Behavior
Segfault :(

#### Environment

Commit: commit bcd47ad60dabba63504b6fd8c691b20f1624caf5
OS: WSL

**Comment by jackgerrits** [comment]
@eisber Are you able to provide a datafile to reproduce this?

**Comment by eisber** [comment]
Prepared the URL and forgot to include... https://mmlspark.blob.core.windows.net/publicwasb/triazines.scale.svmlight

(you need to run %s/ / | / in vi - replace the first space with space + pipe + space)

**Comment by jackgerrits** [comment]
Loading an SGD model into BFGS when using --save_resume doesn't make sense. That is likely what is causing the issue. I haven't looked into what exactly causes the segfault though.

When using save_resume the base learner should not change. That might be the right fix here?

**Comment by eisber** [comment]
ouch... that's an excellent point. Any chance to have an error message?

**Comment by jackgerrits** [comment]
Yes we should have an error in this case for sure

**Comment by jackgerrits** [comment]
This is a tricky one, because for other base learners they require an argument to turn them on. So if there are two base learners enabled, VW would fail saying that one of the base learner's option is unrecognized. Not a great error but at least it would prevent this issue.

The reason why it doesn't work here is that one way to configure GD is to provide no args. So the normal unrecognized thing doesn't happen.

I'm not really sure how to properly detect this case with GD. Also, the error message should be better than unrecognized arg.

**Comment by jackgerrits** [comment]
I was mistaken, after speaking to John you should be able to load an SGD model into BFGS. The important thing though is that it cannot be save_resume.
