### ISSUE TITLE
Publish manylinux wheels

### ISSUE THREAD

**Issue by plannigan** [VowpalWabbit/vowpal_wabbit#2408]
## Short description
Compiled wheels are published for windows. Can `manylinux` wheels also be published?

## **How this suggestion will help you/others**
Compiling from source can be complicated to get all the system dependencies set up properly. By publishing `manylinux` wheels, Linux and OSX users would be able to use the library as easily as Windows users.

## **Example/links if any**
[manylinux repo](https://github.com/pypa/manylinux)

**Comment by jackgerrits** [comment]
Hi @plannigan, we investigated creating wheels on manylinux a while back, and it is definitely something we want to do. At the time there were issues because of Boost being required. We do have plans to remove the program options and python boost dependencies which should hopefully unblock manylinux.

**Comment by peterychang** [comment]
We've resolved most of the issues with binary wheels. Python 3.6-3.8 wheels are now generated automatically via CI for Windows, MacOS, and manylinux.
Python 3.5 and 3.9 is only available on manylinux due to technical issues.

All available wheels will be available on pypi beginning with the next release; in the meantime the CI wheels can be downloaded manually here
https://github.com/VowpalWabbit/vowpal_wabbit/actions

**Comment by jackgerrits** [comment]
Here are links that take you directly to each platform workflow: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#bleeding-edge-latest-commit-on-master
