### ISSUE TITLE
Handling contextual bandit problem with continuous action space

### ISSUE THREAD

**Issue by hardianlawi** [VowpalWabbit/vowpal_wabbit#2427]
### Description

> After reading the documentations, I couldn't find any information regarding continuous action space. I am wondering how should I handle this and if I were to discretize the action, how should I discretize it or how many discrete values etc?

### Link to Documentation Page

> Where is the documentation in question?

**Comment by jackgerrits** [comment]
Hi @hardianlawi, native continuous action support is being worked on currently. Would you be able to elaborate on what guidance you'd like to see for documentation around native continuous action support? As well as documentation about using discretization?

**Comment by hardianlawi** [comment]
From what I understand, there are different ways of dealing with continuous action. I'm not sure which one is being worked on currently.

What I think would be helpful is:

1. How do we deal with continuous action space? Do we discretize the action space or parameterize it by assuming some continuous distribution like gaussian?
2. If we discretize it, how do we deal with the discretization error? Do we use the zooming approach by assuming Lipschitz? Also, what is the recommended exploration method here?
3. If we use continuous distribution, how does the model learn and explore? Is it similar to one-step policy gradient?

**Comment by JohnLangford** [comment]
1) We have a paper here: https://arxiv.org/abs/1902.01520 looking at an approach which I believe in.  In essence, you create a continuous distribution to enable counterfactual evaluation of different strategies.  @rajan-chari has been working on implementing a practical version of this which should be merged in fairly soon. 
3) It is not necessarily one-step policy gradient, because you want to achieve relatively high precision in your choice of action efficiently.  This benefits from some logarithmic time prediction approaches.

**Comment by duburcqa** [comment]
@JohnLangford Do you have any idea of what "fairly soon" means? I was about to start implementing it on my own but if someone is already doing it may be I could wait a little longer.

**Comment by olgavrou** [comment]
Hi @hardianlawi @duburcqa you might want to look at the CATS reduction for continuous action space [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/CATS,-CATS-pdf-for-Continuous-Actions) which was added recently.

**Comment by hardianlawi** [comment]
@olgavrou Do you know if there is any off-policy continuous action space method in the pipeline?

**Comment by olgavrou** [comment]
You can find a new reduction, CBZO, in master, a contextual-bandit style algorithm meant for multi-dimensional, continuous action space, [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Contextual-Bandit-Zeroth-Order-Optimization).

Closing this issue, but feel free to open again if you have more questions.

**Comment by duburcqa** [comment]
Thank you for keeping up on this issue, I found another way to solve my problem since then but I'm happy to see it is moving forward.

**Comment by sumpfork** [comment]
> You can find a new reduction, CBZO, in master, a contextual-bandit style algorithm meant for multi-dimensional, continuous action space, [here](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Contextual-Bandit-Zeroth-Order-Optimization).
> 
> Closing this issue, but feel free to open again if you have more questions.

Hi @olgavrou, do you know whether there are plans to extend the implementation of CBZO in VW to the multidimensional action case?

**Comment by olgavrou** [comment]
@ajay0 do you have any plans regarding extension of cbzo :top: ?

**Comment by ajay0** [comment]
@olgavrou @sumpfork sorry for the delayed response, I somehow missed the @ mention. 

We _do_ have plans to extend to the multidimensional case. We are also planning to include a `tree` policy (in addition to the `constant` and `linear` policy currently available) where the action to take is decided by a decision-tree-like model instead of a a linear model. Unfortunately I don't have a timeline to give yet.
