### ISSUE TITLE
Measure memory usage of VW during inference and reducing it?

### ISSUE THREAD

**Issue by albertlim** [VowpalWabbit/vowpal_wabbit#2469]
Hey folks, very happy VW user here looking for some help.

I'm training hundreds of VW models, and we have about 20 servers that individually load them all. While the results are great, the memory usage of these models all together on each server are getting quite large, into the tens of gigs. Around 50MB per model, even when the raw size is just 150KB or less. As a result we're actively trying to reduce the memory usage of these models during productions.

We've done the low-hanging fruit types, such as reducing bit-precision, reducing the amount of training data. But at this point we've sort of hit a wall.

I was wondering if there were other ways to reduce the memory footprint during inference on production? And any recommendations to see exactly how much memory each model is using? 

We're also using older versions of VW from 2016/2017 because of legacy issues, but if the latest versions using for example slim VW reduce inference memory usage, I'd definitely be making a case to upgrade our software.

**Comment by jackgerrits** [comment]
Hi @albertlim,

Thanks for opening the issue!

I'd like to understand a bit more about your operating environment. Are you using VW as:
- Command line and piping the stdin/stdout? 
- Lib in C++?
- Bound to another language?
- Using the shipped bindings?
- Something else?

You should not need to reduce your training data. This should not have an effect on inference memory consumption. If you are worried about the model size using regularization (explained below) can help.

Things to try:
### Limit number of reused examples
VW internally reuses examples to reduce the amount of allocation required. It keeps a number of these around, it allows the parser to continue processing the input while the learner operates. Reducing this number will have a **large effect** on memory consumption but i may affect runtime performance.

If you are using multiline examples it is very importance that you do not set this number to be smaller than your biggest multiline example. The default value for this arg is 256.

```
--ring_size arg              size of example ring
```

### Reducing `-b`
You already tried this but I thought I should add it to this list. This will reduce the range of hashes are produced, resulting in a smaller weights array.
### Reducing ring buffer size

### Using Regularization
Using regularization will drive weights towards 0 during training. L1 has a greater effect than L2. This may not reduce memory consumption at runtime necessarily because dense weights are used but it will reduce the size of serialized models. 
```
--l1 arg (=0)                l_1 lambda (L1 regularization)
--l2 arg (=0)                l_2 lambda (L2 regularization)
```

Using slim VW is an option, but I would currently recommend against this for now. It is not ready for wide usage and the feature set available there is significantly reduced.

Hope this helps! Let me know if you have any questions.

**Comment by jackgerrits** [comment]
Hopefully this helped answer your question, if not then please feel free to reopen.
