### ISSUE TITLE
Memory leak in Python binding

### ISSUE THREAD

**Issue by rushter** [VowpalWabbit/vowpal_wabbit#2516]
#### Describe the bug

The `vw.finish()` method and class deconstructor do not free memory when using Python bindings.

#### To Reproduce

The code below consumes 1.5GB for a 100MB model.
Each loop iteration increases consumption.

```
import vowpalwabbit.pyvw
import gc

model_path = 'model.vw'

for i in range(15):
    model = vowpalwabbit.pyvw.vw(
        "-t -i {model_path} --json --quiet --probabilities  --loss_function=logistic".format(
            model_path=model_path
        )
    )
    model.finish()
    del model

gc.collect()
print("Time to check memory consumption")
time.sleep(120)
```

#### Environment

`Python 3.8, 8.8.1, macOS`

**Comment by rushter** [comment]
An unrelated question to the maintainers.

Is it possible to compile VW Python binding so that it won't need Boost installed on the system?
If so, why there are no Python wheels for PyPI (precompiled binaries for each system)?

I maintain a Python project with C code. And my CI automatically compiles 20+ wheels for Windows, MacOS, Linux.
I can help you to do the same, but I'm not an expert in C++ and Boost.
If we can "bundle" everything at compilation time, the library will be much easier to use and install.

**Comment by lalo** [comment]
I did some quick debugging using `pympler` and just using `resource`, I was able to repro the memory leak. Then I tried turning this argument to `true` and the memory leak looks like is gone: https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/pylibvw.cc#L72

We should take a closer look, we might be assuming something incorrect on our python finish() call or figure out a proper way to mitigate this scenario.

@peterychang do you have more context regarding the other question?

**Comment by peterychang** [comment]
There are a few reasons why wheels are not generated for Linux or MacOS. Most of these boil down to the fact that we bind against C++ rather than a C interface.

On Linux, this creates some problems with building on the manylinux2010 environment, especially when boost is introduced into the requirements. A fair amount of effort has been spent trying to create wheels from our existing source, but the boost libraries are particularly finicky on that environment.

On MacOS, there are compatibility issues around the removal of libstdc++ from OSX 10.14+. Since the python wrapper is bound to a C++ layer, compatibility needs to be maintained and so the story around it gets a bit muddled.

The resolve these issues, the team is actively working on a C API that all language bindings will build against. This should allow us to break our dependency on boost-python and help deal with the compatibility issues on MacOS

**Comment by lalo** [comment]
@peterychang this issued should be closed right?

**Comment by peterychang** [comment]
We've resolved most of the issues with binary wheels. Python 3.6-3.8 wheels are now generated automatically via CI for Windows, MacOS, and manylinux.
Python 3.5 and 3.9 is only available on manylinux due to technical issues.

All available wheels will be available on pypi beginning with the next release; in the meantime the CI wheels can be downloaded manually here
https://github.com/VowpalWabbit/vowpal_wabbit/actions

**Comment by rushter** [comment]
Good news! Thank you for your work!

**Comment by jackgerrits** [comment]
Here are links that take you directly to each platform workflow: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#bleeding-edge-latest-commit-on-master
