### ISSUE TITLE
vw-hyperopt wan't update since 2015

### ISSUE THREAD

**Issue by aburkov** [VowpalWabbit/vowpal_wabbit#2808]
Hey. The vw-hyperopt tool for hyperparameter tuning wasn't updated since 2015. The API of VW changed significantly since then. Also, vw-hyperopt didn't support some options since the beginning (the author said he will support them). Do you plan to update this script? If not, what tool do you recommend instead?

**Comment by jackgerrits** [comment]
Which file are you referring to? `vw-hyperopt.py` or `vw-hypersearch`?

**Comment by aburkov** [comment]
> Which file are you referring to? `vw-hyperopt.py` or `vw-hypersearch`?

vw-hyperopt.py

**Comment by jackgerrits** [comment]
This file has been worked on by several contributors: https://github.com/VowpalWabbit/vowpal_wabbit/commits/master/utl/vw-hyperopt.py, and it seems this file is still in use by people.

Contributions are certainly welcome. If you have specific bugs or feature requests for the file then I would suggest creating an issue for them so that they can be picked up.

**Comment by jackgerrits** [comment]
Closing this general issue. Please feel free to create specific issues around bugs or feature requests.
