### ISSUE TITLE
Automate Generation and Release of VW NuGets

### ISSUE THREAD

**Issue by dvbarnes** [VowpalWabbit/vowpal_wabbit#2839]
## Short description
Hey all, I noticed VW 8.9.2 was released. Any way we can get the c# bindings nuget package published as well?

## **Possible solution/implementation details**
As a larger item of feedback, any way you all can point me to the build/release process? I'd be happy to work in nuget package pack/publish as part of a PR

**Comment by lokitoth** [comment]
Yes, I am working on putting together a better triggering/automation system for it (stay tuned). For now, just triggered a build manually and will push the package when it is available.

**Comment by lokitoth** [comment]
@dvbarnes: The 8.9.2 package is now available at: https://www.nuget.org/packages/VowpalWabbit/8.9.2

I will keep the issue open to track the remaining work to automate this process.

**Comment by jackgerrits** [comment]
The nugets are automatically generated by this CI: https://github.com/VowpalWabbit/vowpal_wabbit/actions/runs/3796336082

Automated release is another level which I don't think we are ready for at the moment because we release artifacts to many different locations.

I'm going to close this as the most important piece, generation, is available.
