### ISSUE TITLE
Proposal: Interaction expansion as a reduction

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#2963]
# Interaction expansion as a reduction

## Update 1

Moving the expansion to a reduction directly above GD allows us to ignore whether multi or single ex is used. It additionally allows all upper reductions to use a wildcard as well if they wish to. This simplifies things like CCB.

## Update 2

Compat removal is not needed.

## Motivation

After an example is parsed, in the `setup_example` routine, the quadratic wildcards are expanded. However, since `setup_example` can only operate on single examples at a time operations that require an entire `multi_ex` are impossible.

Because of this wildcard interactions are calculated based on the globally seen set of interactions rather than only the interactions seen in a given `multi_ex`.

## Solution

Change wildcard expansion to be calculated as a reduction, since at this point the entire `multi_ex` is available.

If performance proves to be a concern here one approach could be to cache the result. An expansion depends on the input (namespaces present, requested interactions) and such can be cached based on these. Determining how to efficiently create a key to check the cache will need thought here.

~~To ease this process I propose we now remove the legacy model reading code for:~~
- ~~VERSION_FILE_WITH_INTERACTIONS "7.10.2"~~
- ~~VERSION_FILE_WITH_INTERACTIONS_IN_FO "7.10.3"~~

~~For reference, version 7.10 was released Feb 14, 2015.~~

~~Without removing these the encapsulation of interactions as a reduction will be hard to realize. ~~

~~See: #2964~~

EDIT: Nice, but not needed.

## Drawback

Doing this in the reduction stack means that work that used to be able to occur in the parse thread can no longer be done. If the parser is enlightened to `multi_ex`'s then it can be moved back.

**Comment by olgavrou** [comment]
Wildcard interactions are calculated based on globally seen interactions not only due to `multi_ex` but so that they don't have to be calculated again for every parsed (multi)example (since files tend to have examples with same or similar namespaces), so it sort of serves as a global cache.

This looks like a tradeoff between potentially looping over un-needed interactions on every learn/predict call vs generating them for every example. It really depends on the structure of the file. One with the same namespaces throughout will likely benefit from the global approach. One with changing namespaces will likely benefit from the reduction approach.

I like the approach of reduction + cache, I think it will work nicely

**Comment by jackgerrits** [comment]
See #update.

> Moving the expansion to a reduction directly above GD allows us to ignore whether multi or single ex is used. It additionally allows all upper reductions to use a wildcard as well if they wish to. This simplifies things like CCB.

**Comment by jackgerrits** [comment]
This is completed. See: https://github.com/VowpalWabbit/vowpal_wabbit/pull/2993
