### ISSUE TITLE
cb to cb_adf with multiple costs

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#3108]
From a gitter question

#### To Reproduce
input
```
1:1:1.0 2:2 3:3 4:4 | a b c
1:1 2:2:1.0 3:3 4:4 | a b c
1:1 2:2 3:3:1.0 4:4 | a b c
1:1 2:2 3:3 4:4:1.0 | a b c
1:1 2:2:0.7 3:3 4:4 | d e f
```

command line:
`vw -d sampledata.vw --cb 4`

#### Expected behavior
VW can learn from this data as it does if we default to old cb behavior via adding the `--cb_force_legacy` flag

#### Observed Behavior
`[critical] vw (cb_adf.cc:279): cb_adf: badly formatted example, only one cost can be known.`

#### Environment
latest master (8.11)
Ubuntu 18.04

**Comment by lalo** [comment]
Looks like we have to transform the incoming label, split it and create a label with a single cost: right here https://github.com/VowpalWabbit/vowpal_wabbit/blob/26442043bfc5606062b7bc1533d2ad14ffc42d62/vowpalwabbit/cb_to_cb_adf.cc#L39

**Comment by kumpera** [comment]
That would be an invalid conversion because it would not allow the underlying model to learn from multiple costs

**Comment by lalo** [comment]
wiki mentions the following:
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Logged-Contextual-Bandit-Example

The other costs for the other actions are not used for training, but are used only for evaluating the cost of the predictions made by the predictor, instead of the cost estimates from the ips, dm or dr methods. This can also be used with examples where only a subset of actions can be chosen, e.g.:
