### ISSUE TITLE
`--save_resume` to become default for model saving and loading

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpal_wabbit#3163]
When a model is saved currently the default is just to store just the model weights. A flag `--save_resume` is available which additionally saves the trainer state which allows you to continue training additional training state. This is required when resuming for online learning.

We have noticed over time that most users expect to be able to resume training from a saved model and would therefore need to supply the `--save_resume` flag. This is unintuitive for most users. We will be changing default behavior to be as if `--save_resume` were passed, unless `--save_bare` is supplied in which case the behavior will be the old default logic.

The extra state for save resume does increase model size, approximately 2 or 3 orders of magnitude. However, VW models are already very small often in the order of single digit megabytes. It is unlikely to matter practically.

We believe this to be a positive change without any major drawbacks, but it is important to consider this fact if you are currently using VW to initialize weights for a batch training scenario.

## When would I want to use `--save_bare`?
The extra trainer state is not needed for predictions. Therefore, if the model is for predictions only then using `--save_bare` may make sense. Do note thought that the extra trainer state will have no negative impact on predictions so this is only necessary if you want to reduce model size.

If you use VW in a batch setting and only load a model with the intention of initializing weights then the extra trainer state may not be desired as it affects the rate of learning per parameter. In practice, this seems to be insignificant to training performance though. 

## When does this take effect?
The default will change in the next release of VW, 9.0.0. But as always, we opened this issue for discussion in case there are issues with the plan.

**Comment by rajan-chari** [comment]
Instead of 2 or 3 orders of magnitude -- assuming you meant 2x - 3x?

**Comment by jackgerrits** [comment]
I was just repeated what John said, but I do agree. The extra space should be in the ~3 or 4x and not orders of magnitude

**Comment by lokitoth** [comment]
I suspect this will depend a little on the base learner and algorithm.

Most differences are all contained to the GD::save_load_regressor/GD::save_load_online_state. There the number of additional values stored depends on the true base learner / algorithm:

| Base Learner / Variant | Extra Floats Per Weight | Notes |
| -----------:------------ | ------------------------- | :------- |
| GD - adaptive+normalized | 2 | |
| GD - adaptive | normalized | 1 | |
| GD - plain                            | 0 | |
| OjaNewton                          | 0 | |
| SVRG                                   | 0 | Note that SVRG requests extra space for parameter always, but does not seem to do anything extra special in save-resume |
| FTRL - Proximal-FTRL          | 2 | |
| FTRL - PiSTOL                      | 3 | |
| FTRL - Coin Betting             | 5 | |


Additional considerations:
* PLT adds one float for every node in addition to what the base learners generate. 
* CB Bag multiplies this by the size of the bag, because it multi-instances the underlying learner, so the number of extra weights is multiplied by the bag size - I am not sure if there are others like this.
* CBZO keeps the radius (in options) only in the save_resume case: Is this a bug?
