### ISSUE TITLE
Inconsistencies with wildcard & hex namespaces

### ISSUE THREAD

**Issue by memeplex** [VowpalWabbit/vowpal_wabbit#3217]
#### Describe the bug

There are some inconsistencies in the way different arguments handle "special" namespaces (wildcards, hex codes).

#### To Reproduce

* `vw --quadratic \\x20\\x20` fails with `error, quadratic features must involve two sets`.
* Similarly `vw --cubic \\x20\\x20\\x20` fails with `error, cubic features must involve three sets`.
* But `--interactions` happily accepts hex codes to achieve the same. Also `--lrq`.
* `--quadratic` can take `::` wildcards but `--lrq` can't handle them (it doesn't throw an error though).

#### Expected behavior

All arguments that take namespace arguments should handle `:` as wildcard and understand hex codes.

At least the "hex codes" part is documented in https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-line-arguments:

> note: \xFF notation could be used to define namespace by its character's hex code (FF in this example). \x is case sensitive and \ shall be escaped in some shells like bash (-q \\xC0\\xC1). This format is supported **in any command line argument which accepts namespaces**.

#### Observed Behavior

As described above.

#### Environment

What version of VW did you use? 8.11.0

What OS or language did you use? macOS Big Sur, command line and python bindings.

**Comment by jackgerrits** [comment]
There are inconsistencies in how namespace specification is handled, mainly for expansion of wildcards. This is usually due to a reduction implementing its own base learning algorithm that is less commonly used and therefore not as well supported.

There's two things here I think:
- hex code expansion is done after the check for length, which is clearly a bug. Swapping the length check to be after the hex code expansion should resolve this for quadratics and cubics
- Implementing wildcard expansion in lrq would be a feature request (Looks like there's a todo for it in there) https://github.com/VowpalWabbit/vowpal_wabbit/blob/44d29acdc59fdb45f9f3aae25aa234a1f0e64c0b/vowpalwabbit/lrq.cc#L201

**Comment by memeplex** [comment]
> Implementing wildcard expansion in lrq would be a feature request (Looks like there's a todo for it in there)

Maybe for the time being an error could be thrown instead of silently ignoring the wildcard namespace, so as to not let the user believing it's working as expected while it's not?

**Comment by memeplex** [comment]
Or a warning could be added to the command line documentation, which is simpler although not as safe.

**Comment by jackgerrits** [comment]
Totally agree, a warning would be considerably better than current behaviour.

**Comment by jackgerrits** [comment]
> - vw --quadratic \\x20\\x20 fails with error, quadratic features must involve two sets.
> - Similarly vw --cubic \\x20\\x20\\x20 fails with error, cubic features must involve three sets.

Should both be resolved by https://github.com/VowpalWabbit/vowpal_wabbit/pull/3230.

Remaining mitigation is to emit an error if a wildcard is used with lrq. Longer term is to support wilcards but that is much more involved.

**Comment by memeplex** [comment]
> Remaining mitigation is to emit an error if a wildcard is used with lrq. Longer term is to support wilcards but that is much more involved.

Makes sense to me. Thanks!
