### ISSUE TITLE
Sequence Predictions Training with SEARN and DAgger

### ISSUE THREAD

**Issue by Sandy4321** [VowpalWabbit/vowpal_wabbit#3297]
### Description

> A brief description of the error, missing documentation or what you would like added
it is not clear where to find information how to use in python Sequence Predictions Training
as mentioned in https://docplayer.net/14088260-Vowpal-wabbit-7-tutorial-stephane-ross.html
Sequence Predictions Training and Testing
•For SEARN:./vw--d train.txt -c --passes 10 --searnk --searn_tasksequence --searn_beta0.5 --searn_passes_per_policy2 -f policy.vw
•For DAgger:./vw--d train.txt -c --passes 10 --searnk --searn_tasksequence --searn_as_dagger0.0001 -f policy.vw

Is option still avaialbe?

it would great to have 0 to end example with some data set 

### Link to Documentation Page

> Where is the documentation in question?

**Comment by jackgerrits** [comment]
Hi @Sandy4321,

The talk you pointed to is for an older version, some things have changed. It looks like `searn` was renamed to `search`. (I think `searn` stood for search and learn)

-   replace `searn` => `search`
-   put in a value for `k` and put a space between `search` and `k`  (i.e.  `--search <k>`)
-   `tasksequence` => `task sequence` (i.e. `--search_task sequence`)
-   The way to turn on `DAGGER` is to use `--search_interpolation policy`, rather than `--searn_as_dagger`

Note, I am not sure of the status of [this issue](https://github.com/vowpalwabbit/vowpal_wabbit/issues/2175) but keep it in mind if you run into any problems.

Also, there is an example notebook using Python which can be found here: https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/examples/search_sequence.html

**Comment by Sandy4321** [comment]
great 
thanks for soon answer
may you share some links to read about theoretical base for this code ?

**Comment by jackgerrits** [comment]
You can read more about search here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Learning-to-Search-Sub-System

**Comment by Sandy4321** [comment]
super
great material thanks
1

by the way this link 
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb
from reference
"For python implementation, please see this ipython notebook"
out to date

can yo help to find correct link please 
2
https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb

this link as well 
please

I try to learn how you predict sequences 
seems to be you have something really good..
the all material as welcome
especially beginners material to understand ideas

**Comment by jackgerrits** [comment]
I've updated the link to point here: https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/examples/index.html
