### ISSUE TITLE
there is no --multilabel_oaa  in Command-Line-Arguments wiki web page

### ISSUE THREAD

**Issue by Sandy4321** [VowpalWabbit/vowpal_wabbit#3312]
### Description
there is no --multilabel_oaa mentioning in
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments

may you share some full example from 0 to end for
--multilabel_oaa option
especially with data 
definitely it is not multiclass case 
then how to create target data ?

best case would share code example  python 
by analogy with 
    Examples
    --------
    >>> import numpy as np
    >>> X = np.array([ [10, 10], [8, 10], [-5, 5.5], [-5.4, 5.5], [-20, -20],  [-15, -20] ])
    >>> y = np.array([1, 1, 2, 2, 3, 3])
    >>> from vowpalwabbit.sklearn_vw import VWMultiClassifier
    >>> model = VWMultiClassifier(oaa=3, loss_function='logistic')
    >>> _ = model.fit(X, y)
    >>> model.predict_proba(X)
    array([[0.38928846, 0.30534211, 0.30536944],
           [0.40664235, 0.29666999, 0.29668769],
           [0.52324486, 0.23841164, 0.23834346],
           [0.5268591 , 0.23660533, 0.23653553],
           [0.65397811, 0.17312808, 0.17289382],
           [0.61190444, 0.19416356, 0.19393198]])

### Link to Documentation Page
https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
> Where is the documentation in question?

**Comment by jackgerrits** [comment]
It seems there is no docs for that reduction unfortunately. For an example of usage you can look at [this test](https://github.com/VowpalWabbit/vowpal_wabbit/blob/6670fc8db7cc44e65f84e5538c9bf285b204dd1c/test/RunTests#L1258).

**Comment by jackgerrits** [comment]
The `cache_file` option doesn't make a whole lot of sense when consuming VW via PyVW. Two things could happen:
- If the file exists it will read from it if you decide to run the driver
- If the file does not exist VW will write examples to it as they are parsed (technically as they are given to `setup_example`) but that fact is a little bit abstracted in PyVW.

Additionally, [`finish`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.pyvw.html?highlight=finish#vowpalwabbit.pyvw.vw.finish)  might be needed to close the file when VW is done.

What are you trying to use the cache for in this instance. This is certainly one of those very counterintuitive things because of the command line focus of the library

**Comment by Sandy4321** [comment]
"Additionally, finish might be needed to close the file when VW is done"
as written above
-------------------
but this code not running correctly
VWmodel_simple = pyvw.vw(
cache_file = 'my_VW_2.cache',
passes = 3,
learning_rate = 0.1,
l2 = ridge_lambda,
loss_function = loss_function,
)

code run never finished


---------------------------------
then I can not use "finish" since code never move to next line 
code run just blocked after theses lines

I updated vw version to latest but still

********************************
this works
from vowpalwabbit import pyvw
ridge_lambda = 0.001
loss_function = 'squared'
q=0
VWmodel_simple  = pyvw.vw(
    learning_rate = 0.1,
    l2 = ridge_lambda,
    loss_function = loss_function,    
)
********************************

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
this does not work
from vowpalwabbit import pyvw
ridge_lambda = 0.001
loss_function = 'squared'
q=0
VWmodel_simple  = pyvw.vw(
    learning_rate = 0.1,
    l2 = ridge_lambda,
    loss_function = loss_function,    
)


|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
never finish to run

**Comment by Sandy4321** [comment]
correction

|||||||||||||||||||||||||||||||||||||
this does not work
VWmodel_simple  = pyvw.vw(
    cache_file =  'my_VW_2.cache',
    passes = 3,
    learning_rate = 0.1,
    l2 = ridge_lambda,
    loss_function = loss_function,    
)
||||||||||||||||||||||||||||||||||
never finish to run

**Comment by Sandy4321** [comment]
this also never finish
![image](https://user-images.githubusercontent.com/11426119/141373886-c8ba509c-0d52-4f22-aa24-fd33ec561318.png)

**Comment by Sandy4321** [comment]
vowpalwabbit.__version__
'8.11.0'

**Comment by jackgerrits** [comment]
When you say "passes" for PyVW it is expecting you to have supplied a datafile. When you don't supply a data file (`-d`) VW implicitly uses stdin. So what you are seeing is VW sitting waiting to read stdin.

It's counterintuitive because in the way you are invoking PyVW it is sort of behaving like a command line invocation.

If you wish to use PyVW interactively instead of using it to process a file then you must avoid passing `-d` or `--passes`. See here for the check: https://github.com/VowpalWabbit/vowpal_wabbit/blob/e72cad55fb558389b51303d071377eb0ad1a2078/python/vowpalwabbit/pyvw.py#L372
