### ISSUE TITLE
Github produced tarball does not include submodules which leads to build failures due to missing libraries in `ext_libs`

### ISSUE THREAD

**Issue by dkasak** [VowpalWabbit/vowpal_wabbit#3466]
#### Describe the bug
Trying to build 8.11.0 fails with

```
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: program_options system 
CMake Error at ext_libs/ext_libs.cmake:11 (add_subdirectory):
  The source directory

    /home/dkasak/code/dkasak/packages/aur_packages/vowpal_wabbit/src/vowpal_wabbit-8.11.0/ext_libs/fmt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:243 (include)


CMake Error at ext_libs/ext_libs.cmake:25 (add_subdirectory):
  The source directory

    /home/dkasak/code/dkasak/packages/aur_packages/vowpal_wabbit/src/vowpal_wabbit-8.11.0/ext_libs/spdlog

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:243 (include)
```

These are normally git submodules, so it looks like their content wasn't properly included into the release tarball?

#### To Reproduce
1. Download `https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/8.11.0.tar.gz`.
2. Unpack `tar xzvf 8.11.0.tar.gz`.
3. `cd` into the directory.
4. Run `cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DVW_INSTALL=ON
` in an attempt to build.

The build fails with the above error message.

#### Expected behavior
The release tarball should be self-contained and buildable.

#### Environment
What version of VW did you use? 8.11.0
What OS or language did you use? Arch Linux

**Comment by olgavrou** [comment]
Hi @dkasak github release tarballs do not include submodules by design

The best way to work around that currently is to clone a specific release `git clone git@github.com:VowpalWabbit/vowpal_wabbit.git --branch 8.11.0 --recursive` and by using `--recursive` it will also checkout the submodules

I have removed the `bug` label and added the `feature request` so that we can potentially create a workflow that produces tarballs with the submodules on our release pipeline. If that is something you want to take on we will be happy to ensure it is part of future releases
