### ISSUE TITLE
Bug report on vowpal_wabbit( AddressSanitizer: FPE)_offset_tree_cont_predict

### ISSUE THREAD

**Issue by afosscontact** [VowpalWabbit/vowpal_wabbit#3543]
Describe the bug
A bug was found within the vowpal_wabbit. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using vowpal_wabbit. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "offset_tree_cont_predict". 
This may cause problems in the use of libraries

How To Reproduce
1. Download the attached file
2. Execute  make_vowpal_wabbit_bug2.sh
3. vowpal_wabbit/build/test/unit_test/vw-unit-test.out -t offset_tree_cont_predict

==46607==ERROR: AddressSanitizer: FPE on unknown address 0x000000d1d3ff (pc 0x000000d1d3ff bp 0x7ffcc60b2990 sp 0x7ffcc60b2280 T0)
    #0 0xd1d3ff in VW::cats_tree::min_depth_binary_tree::build_tree(unsigned int, unsigned int) vowpal_wabbit/vowpalwabbit/cats_tree.cc:97

Platform (please complete the following information):
OS: Ubuntu 18.04
[vowpal_bug2.tar.gz](https://github.com/VowpalWabbit/vowpal_wabbit/files/7765937/vowpal_bug2.tar.gz)

**Comment by bassmang** [comment]
Hi @afosscontact,
This error is also resolved by this PR: https://github.com/VowpalWabbit/vowpal_wabbit/pull/3544

**Comment by junsik-kim0** [comment]
Thank you for the fast fix
This bug found in Fuzzing technology we are studying
If you have completed the modification for this bug, I want to issue CVE ID
Is it possible to issue CVE ID?
If you are enabled, you want to be issued under the name Autofuzz.
Because I am being issued as a NickName called Autofuzz in CVEs found by this Fuzzing technology.
