### ISSUE TITLE
audit_example does not work in Python with JSON-encoded example

### ISSUE THREAD

**Issue by chanind** [VowpalWabbit/vowpal_wabbit#3794]
### Describe the bug

The python version of VW can handle JSON encoded string examples for training and prediction when using the `--json` option, however the [`audit_example()`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.pyvw.pylibvw.html#vowpalwabbit.pyvw.pylibvw.vw.audit_example) method, which has an identical method signature to [`predict()`](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/reference/vowpalwabbit.pyvw.pylibvw.html#vowpalwabbit.pyvw.pylibvw.vw.predict), yet errors given identical input.

### How to reproduce

```python
import vowpalwabbit
import json

vw = vowpalwabbit.Workspace('--cb_explore_adf --json --epsilon 0.1')

example = {
  'User': { 'age': 20 },
  '_multi': [
    {'Action': { 'id': '123', 'size': 'big' }},
    {'Action': { 'id': 'xyz', 'size': 'small' }}
  ]
}

vw.predict(json.dumps(example)) # OK!
vw.audit_example(json.dumps(example)) # ERROR! 
# Python argument types in vw.audit_example(Workspace, Workspace, str) did not match C++ signature: audit_example(boost::shared_ptr<VW::workspace>, boost::shared_ptr<example>)

```

### Version

9.0.1

### OS

macOS

### Language

Python

**Comment by jackgerrits** [comment]
Interesting, I haven't noticed that function before. Looks like it just runs an example through the audit process that normally happens at the base learner. So, keep in mind this will just print some things out to `stdout` rather than returning something to Python.

Looking at the signature of that function you must call it with an `Example` object not a string as you've done. 
Since you're using a `multi_ex` (list of examples) you'll need to iterate over each example in turn as well.  We can use `Workspace.parse` to get a `multi_ex` from the raw json text and then go from there. It's also important that the workspace is initialized with audit enabled so that the extra information is recorded during parsing.
```python
import vowpalwabbit
import json

vw = vowpalwabbit.Workspace('--cb_explore_adf --json --epsilon 0.1 --audit --quiet')

example = {
  'User': { 'age': 20 },
  '_multi': [
    {'Action': { 'id': '123', 'size': 'big' }},
    {'Action': { 'id': 'xyz', 'size': 'small' }}
  ]
}

examples = vw.parse(json.dumps(example))
for i, example in enumerate(examples):
    print(f"Example #{i}:")
    vw.audit_example(example)
vw.finish_example(examples)
```

Produces the following to `stdout`:
```
Example #0:
0
        User^age:143891:20:0@0  Constant:116060:1:0@0
Example #1:
0
        Action^id123:141247:1:0@0       Action^sizebig:125893:1:0@0     Constant:116060:1:0@0
Example #2:
0
        Action^idxyz:228274:1:0@0       Action^sizesmall:178939:1:0@0   Constant:116060:1:0@0
```

**Comment by jackgerrits** [comment]
Going to go ahead and close this, please feel free to reopen or open a new issue if you have any problems.
