### ISSUE TITLE
It is not possible to assemble a project

### ISSUE THREAD

**Issue by Manfredik** [VowpalWabbit/vowpal_wabbit#4166]
### Describe the bug

It is not possible to assemble a project

I do everything according to the instructions, but the result is the same, I can't get the cli version

### How to reproduce

Cmake command
cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="./ext_libs/vcpkg/scripts/buildsystems/vcpkg.cmake" -DFMT_SYS_DEP:BOOL="ON" -DRAPIDJSON_SYS_DEP:BOOL="ON" -DSPDLOG_SYS_DEP:BOOL="ON" -DVW_BOOST_MATH_SYS_DEP:BOOL="ON" -DVW_GTEST_SYS_DEP:BOOL="ON" -DVW_ZLIB_SYS_DEP:BOOL="ON"  -DBUILD_TESTING:BOOL="OFF" -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 -G "Visual Studio 17 2022"-DVW_INSTALL=ON

Build command
 cmake --build build 

Install Command 
cmake --install build

C:\vw\vowpal_wabbit>cmake --install build
-- Install configuration: "Release"
-- Installing: C:/Program Files/vowpal_wabbit/lib/pkgconfig/libvw_c_wrapper.pc
-- Installing: C:/Program Files/vowpal_wabbit/lib/cmake/VowpalWabbit/VowpalWabbitTargets.cmake
-- Installing: C:/Program Files/vowpal_wabbit/lib/cmake/VowpalWabbit/VowpalWabbitTargets-release.cmake
-- Installing: C:/Program Files/vowpal_wabbit/lib/cmake/VowpalWabbit/VowpalWabbitConfigVersion.cmake
-- Installing: C:/Program Files/vowpal_wabbit/lib/cmake/VowpalWabbit/VowpalWabbitConfig.cmake
-- Installing: C:/Program Files/vowpal_wabbit/include/nonstd/
-- Installing: C:/Program Files/vowpal_wabbit/include/nonstd//string_view.h
CMake Error at build/vowpalwabbit/allreduce/cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "C:/vw/vowpal_wabbit/build/vowpalwabbit/allreduce/Release/vw_allreduce.lib":
  No such file or directory.
Call Stack (most recent call first):
  build/vowpalwabbit/cmake_install.cmake:38 (include)
  build/cmake_install.cmake:82 (include)

Despite the Release string parameter, Debug folders are created everywhere
And there is no file in the Debug folder vw_allreduce.lib but a file vw_allreduced.lib

### Version

9.4

### OS

Windows 11

### Language

Cmake

### Additional context

-- VowpalWabbit Version: 9.4.0
-- WinSDK Version: 10.0.16299.0
-- Running vcpkg install

**Comment by jackgerrits** [comment]
Visual studio is a multi-config generator, `CMAKE_BUILD_TYPE` only works as expected when using single config generators such as `Ninja`. 

You can select the configuration when running the build command like so:
```sh
cmake --build build --config Release
```

You saw debug everywhere because the default for visual studio is the `debug` config.

Also, you don't need to run `cmake --install` unless you want to actually install the build outputs to your `C:\program files (x86)` directory. After running `cmake --build build` the build outputs should be available in the `build` dir. The `vw.exe` binary might be in the `vowpalwabbit/cli` subdirectory, you might need to search for it in `build/` since I am not sure of the structure of directories when using the visual studio generator.

**Comment by Manfredik** [comment]
Thanks
